selection_all = [
[
    "Women and girls",
    "LGBTQIA+ people",
    "Elderly",
    "Children & Youth",
    "Indigenous and traditional communities",
    "Ethnic or religious minorities",
    "Refugees",
    "Disabled People",
    "Low Income Communities",
    ""
],
[
    "Food and Agriculture",
    "Health",
    "Human Settlements",
    "Coastal and Oceans",
    "Infrastructure",
    "Water and Nature",
    "Planning and Policy: Cross-cutting",
    "Finance: Cross-cutting",
    ""
],
[
    "Monitoring and mapping of hazards and vulnerabilities",
    "Climate services and modelling",
    "Generation and processing of data",
    "Early warning systems",
    "Emergency preparedness",
    "Environmental governance and resource management systems",
    "Environmental laws and regulatory framework",
    "Building regulations and standards for climate resilience",
    "Protected areas and property rights definitions",
    "Institutional-led climate adaptation planning processes",
    "Measures to improve air quality and reduce pollution",
    "Green infrastructure and other engineered nature-based solutions",
    "Conservation and restoration of terrestrial and aquatic ecosystems",
    "Critical Infrastructure and Protective Systems",
    "Coastal Infrastructure Protection",
    "Energy efficiency and renewable energy technologies",
    "Water security and quality",
    "Health services",
    "Food safety and sustainable services",
    "Agricultural, livestock, forestry and aquiacultural practices actions",
    "Social protection actions",
    "Community-based inclusive and participatory risk reduction",
    "Climate hazard communication, information, and technology awareness",
    "Knowledge building for resilience",
    "Research and collaboration actions",
    "Livelihood diversification and social economy",
    "Climate insurance and risk transfer",
    "Financial and investment tools in case of climate disasters",
    "Economic incentives",
    ""
],
[
    "Water stress (urban focus)",
    "Water stress (rural focus)",
    "Extreme heat",
    "Extreme cold",
    "Drought (agriculture focus)",
    "Drought (other sectors)",
    "Urban flood",
    "River flood",
    "Coastal flood",
    "Tropical Cyclone",
    "Snow, Ice",
    "Wildfire",
    "Extreme wind",
    "Oceanic Events",
    "Other coastal events",
    ""
],
[
    "Individuals",
    "Companies",
    "Regions",
    "Cities",
    "Natural-Systems",
    ""
],
[
    "Afghanistan",
    "Albania",
    "Algeria",
    "Andorra",
    "Angola",
    "Antigua and Barbuda",
    "Argentina",
    "Armenia",
    "Australia",
    "Austria",
    "Azerbaijan",
    "Bahamas",
    "Bahrain",
    "Bangladesh",
    "Barbados",
    "Belarus",
    "Belgium",
    "Belize",
    "Benin",
    "Bhutan",
    "Bolivia, Plurinational State of",
    "Bosnia and Herzegovina",
    "Botswana",
    "Brazil",
    "Brunei Darussalam",
    "Bulgaria",
    "Burkina Faso",
    "Burundi",
    "Cambodia",
    "Cameroon",
    "Canada",
    "Cape Verde",
    "Central African Republic",
    "Chad",
    "Chile",
    "China",
    "Colombia",
    "Comoros",
    "Congo",
    "Congo, the Democratic Republic of the",
    "Costa Rica",
    "Côte d'Ivoire",
    "Croatia",
    "Cuba",
    "Cyprus",
    "Czech Republic",
    "Denmark",
    "Djibouti",
    "Dominica",
    "Dominican Republic",
    "Ecuador",
    "Egypt",
    "El Salvador",
    "Equatorial Guinea",
    "Eritrea",
    "Estonia",
    "Ethiopia",
    "Finland",
    "France",
    "Gabon",
    "Gambia",
    "Georgia",
    "Germany",
    "Ghana",
    "Greece",
    "Grenada",
    "Guatemala",
    "Guinea",
    "Guinea-Bissau",
    "Guyana",
    "Haiti",
    "Honduras",
    "Hungary",
    "Iceland",
    "India",
    "Indonesia",
    "Iran, Islamic Republic of",
    "Iraq",
    "Ireland",
    "Israel",
    "Italy",
    "Jamaica",
    "Japan",
    "Jordan",
    "Kazakhstan",
    "Kenya",
    "Korea, Republic of",
    "Kuwait",
    "Kyrgyzstan",
    "Lao People's Democratic Republic",
    "Latvia",
    "Lebanon",
    "Lesotho",
    "Liberia",
    "Libyan Arab Jamahiriya",
    "Liechtenstein",
    "Lithuania",
    "Luxembourg",
    "Macedonia, the former Yugoslav Republic of",
    "Madagascar",
    "Malawi",
    "Malaysia",
    "Mali",
    "Malta",
    "Mauritania",
    "Mauritius",
    "Mexico",
    "Micronesia, Federated States of",
    "Moldova, Republic of",
    "Mongolia",
    "Montenegro",
    "Morocco",
    "Mozambique",
    "Myanmar",
    "Namibia",
    "Nepal",
    "Netherlands",
    "New Zealand",
    "Nicaragua",
    "Niger",
    "Nigeria",
    "North Korea",
    "Norway",
    "Oman",
    "Pakistan",
    "Palestinian Territory, Occupied",
    "Panama",
    "Papua New Guinea",
    "Paraguay",
    "Peru",
    "Philippines",
    "Poland",
    "Portugal",
    "Puerto Rico",
    "Qatar",
    "Romania",
    "Russian Federation",
    "Rwanda",
    "Saint Vincent and the Grenadines",
    "Samoa",
    "Sao Tome and Principe",
    "Saudi Arabia",
    "Senegal",
    "Serbia",
    "Sierra Leone",
    "Singapore",
    "Slovakia",
    "Slovenia",
    "Solomon Islands",
    "Somalia",
    "Somaliland",
    "South Africa",
    "South Sudan",
    "Spain",
    "Sri Lanka",
    "Sudan",
    "Suriname",
    "Swaziland",
    "Sweden",
    "Switzerland",
    "Syrian Arab Republic",
    "Taiwan, Province of China",
    "Tajikistan",
    "Tanzania, United Republic of",
    "Thailand",
    "Timor-Leste",
    "Togo",
    "Tonga",
    "Trinidad and Tobago",
    "Tunisia",
    "Turkey",
    "Turkmenistan",
    "Uganda",
    "Ukraine",
    "United Arab Emirates",
    "United Kingdom",
    "United States of America",
    "Uruguay",
    "Uzbekistan",
    "Vanuatu",
    "Venezuela, Bolivarian Republic of",
    "Viet Nam",
    "Western Sahara",
    "Yemen",
    "Zambia",
    "Zimbabwe",
    ""
],
[
    "Africa",
    "Asia",
    "Europe",
    "Latin America and the Caribbean",
    "Northern America",
    "Oceania",
    ""
],
[
    "South Asia",
    "Europe & Central Asia",
    "Middle East & North Africa",
    "Sub-Saharan Africa",
    "Latin America & Caribbean",
    "East Asia & Pacific",
    "North America",
    ""
],
[
    "Southern Asia",
    "Southern Europe",
    "Northern Africa",
    "Middle Africa",
    "Caribbean",
    "South America",
    "Western Asia",
    "Australia and New Zealand",
    "Western Europe",
    "Eastern Europe",
    "Central America",
    "Western Africa",
    "Southern Africa",
    "Eastern Africa",
    "South-Eastern Asia",
    "Northern America",
    "Eastern Asia",
    "Northern Europe",
    "Central Asia",
    "Melanesia",
    "Polynesia",
    "Micronesia",
    ""
]
]
